
image:
  file: .gitpod.Dockerfile
  context: .
tasks:
  # An regular npm-based setup with direnv allow for your dotenv file
  - init: |
      mkdir /workspace/.deno-cache
      echo "export DENO_DIR=/workspace/.deno-cache" >> .envrc
    before: |
      direnv allow || true
      deno cache lib/@community-radar-recaptime/content-warnings/deps.ts
    command: echo hi mom!
    env:
      DENO_DIR: /workspace/.deno-cache
vscode:
  extensions:
    - vivaxy.vscode-conventional-commits
    - mikestead.dotenv
    - eamodio.gitlens
    - akosyakov.gitpod-monitor
    - exiasr.hadolint
    - esbenp.prettier-vscode
    - timonwong.shellcheck
    - donjayamanne.githistory
    - codezombiech.gitignore
    - ms-azuretools.vscode-docker
